import { jsPDF } from 'jspdf';

interface CropReportData {
  soilType: string;
  landSize: number;
  location: string;
  season: string;
  recommendations: Array<{
    cropName: string;
    confidence: number;
    expectedPrice: number;
    expectedCost: number;
    expectedProfit: number;
    explanation: string;
  }>;
}

interface DiseaseReportData {
  diseaseName: string;
  confidence: number;
  symptoms: string;
  treatment: string;
  organicSolution: string;
  chemicalSolution: string;
  prevention: string;
}

export const generateCropPDF = (data: CropReportData) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(22, 163, 74); // primary-600 green
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('KrishiMitra AI - Crop Suggestions', 15, 25);
  
  doc.setFontSize(10);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 150, 25);

  // Input Parameter details
  doc.setTextColor(30, 41, 59); // text-slate-800
  doc.setFontSize(14);
  doc.text('Farm input Profile:', 15, 55);
  
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`• Soil Type: ${data.soilType}`, 15, 65);
  doc.text(`• Farm Size: ${data.landSize} Acres`, 15, 72);
  doc.text(`• Location: ${data.location}`, 15, 79);
  doc.text(`• Season: ${data.season}`, 15, 86);

  // Recommendations
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Top Crop Recommendations:', 15, 100);

  let startY = 110;
  data.recommendations.forEach((crop, idx) => {
    if (startY > 250) {
      doc.addPage();
      startY = 25;
    }
    
    doc.setFillColor(248, 250, 252); // soft slate background
    doc.rect(15, startY - 5, 180, 45, 'F');
    
    doc.setTextColor(22, 163, 74); // green
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(12);
    doc.text(`${idx + 1}. ${crop.cropName} (${(crop.confidence * 100).toFixed(0)}% confidence)`, 20, startY + 2);
    
    doc.setTextColor(100, 116, 139); // gray
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.text(`Price Outlook: Rs. ${crop.expectedPrice}/quintal  |  Estimated Cost: Rs. ${crop.expectedCost}/quintal  |  Net Margin: Rs. ${crop.expectedProfit}/quintal`, 20, startY + 9);
    
    doc.setTextColor(30, 41, 59); // dark slate
    const splitText = doc.splitTextToSize(`Details: ${crop.explanation}`, 170);
    doc.text(splitText, 20, startY + 16);

    startY += 52;
  });

  // Footer banner
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text('This reports are advisory and generated by artificial intelligence. Verify with local KVK before sowing.', 15, 285);

  doc.save(`krishimitra-crop-report-${Date.now()}.pdf`);
};

export const generateDiseasePDF = (data: DiseaseReportData) => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(22, 163, 74); // green
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('KrishiMitra AI - Disease Analysis', 15, 25);
  doc.setFontSize(10);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 25);

  // Diagnosis summary
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(16);
  doc.text(`Diagnosis: ${data.diseaseName}`, 15, 55);
  
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`Analysis Match Accuracy: ${(data.confidence * 100).toFixed(0)}%`, 15, 63);

  // Symptoms
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Identified Symptoms:', 15, 75);
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  let splitText = doc.splitTextToSize(data.symptoms, 180);
  doc.text(splitText, 15, 82);

  let currentY = 82 + (splitText.length * 5) + 8;

  // Immediate Action / Organic Treatment
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Organic Bio-Control measures:', 15, currentY);
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  splitText = doc.splitTextToSize(data.organicSolution, 180);
  doc.text(splitText, 15, currentY + 7);

  currentY = currentY + 7 + (splitText.length * 5) + 8;

  // Chemical Treatment
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Chemical Control measures & Dosages:', 15, currentY);
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  splitText = doc.splitTextToSize(data.chemicalSolution, 180);
  doc.text(splitText, 15, currentY + 7);

  currentY = currentY + 7 + (splitText.length * 5) + 8;

  // Prevention
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Long-term Prevention measures:', 15, currentY);
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  splitText = doc.splitTextToSize(data.prevention, 180);
  doc.text(splitText, 15, currentY + 7);

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text('AI diagnosis is based on leaf imagery. Confirm with physical inspection if necessary.', 15, 285);

  doc.save(`krishimitra-disease-report-${Date.now()}.pdf`);
};
